# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
