# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='downvotes',
        ),
        migrations.AddField(
            model_name='link',
            name='report',
            field=models.BooleanField(default=False),
        ),
    ]
