# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-27 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0003_auto_20160826_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='link',
            old_name='user',
            new_name='poster',
        ),
        migrations.RemoveField(
            model_name='link',
            name='report',
        ),
        migrations.RemoveField(
            model_name='link',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='link',
            name='voted',
        ),
        migrations.AddField(
            model_name='vote',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.Link'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
